// ── Static recipe database ───────────────────────────────────────────────────
// All macros are per serving. Recipe data sourced from MyProtein, Jenneatsgoood,
// and Muscle & Strength recipe collections.

export type RecipeCategory =
  | "Poultry"
  | "Fish"
  | "Beef"
  | "Vegetarian"
  | "Plant-based"
  | "Sweet"
  | "Breakfast"
  | "Air Fryer";

export const RECIPE_CATEGORIES: RecipeCategory[] = [
  "Poultry",
  "Fish",
  "Beef",
  "Vegetarian",
  "Plant-based",
  "Sweet",
  "Breakfast",
  "Air Fryer",
];

export interface RecipeIngredient {
  item: string;
  amount: string; // "200g", "1 cup", "2 tbsp" — kept as display string
}

export interface RecipePreset {
  id: string;
  name: string;
  category: RecipeCategory;
  source: string;
  sourceUrl?: string;
  image?: string;    // URL to recipe photo
  calories: number;  // per serving
  protein: number;   // grams
  carbs: number;     // grams
  fat: number;       // grams
  servings: number;
  prepTime?: number; // minutes
  cookTime?: number; // minutes
  ingredients: RecipeIngredient[];
  instructions: string[];
  tags?: string[];
}

export const recipeDatabase: RecipePreset[] = [
  // ── Poultry ────────────────────────────────────────────────────────────────
  {
    id: "spicy-chicken-couscous",
    name: "Spicy Chicken with Couscous",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/spicy-chicken-with-couscous-macro-balanced-meals/",
    image: "/images/recipes/spicy-chicken-couscous.png",
    calories: 284, protein: 50, carbs: 22, fat: 5, servings: 1,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Chicken breast", amount: "200g" },
      { item: "Couscous", amount: "60g" },
      { item: "Paprika", amount: "1 tsp" },
      { item: "Cayenne pepper", amount: "1/2 tsp" },
      { item: "Garlic powder", amount: "1 tsp" },
      { item: "Lemon juice", amount: "1 tbsp" },
      { item: "Mixed vegetables", amount: "100g" },
    ],
    instructions: [
      "Season chicken breast with paprika, cayenne, and garlic powder.",
      "Grill or pan-fry chicken for 6-7 minutes per side until cooked through.",
      "Cook couscous according to package directions.",
      "Sauté mixed vegetables until tender.",
      "Slice chicken and serve over couscous with vegetables. Finish with lemon juice.",
    ],
    tags: ["high-protein", "low-fat", "meal-prep", "quick"],
  },
  {
    id: "chicken-curry-gyros",
    name: "Chicken Curry Gyros",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/chicken-curry-gyros-fakeaway-recipe/",
    image: "/images/recipes/chicken-curry-gyros.png",
    calories: 541, protein: 40, carbs: 52, fat: 17, servings: 2,
    prepTime: 15, cookTime: 20,
    ingredients: [
      { item: "Chicken thigh (boneless)", amount: "400g" },
      { item: "Greek yogurt", amount: "100g" },
      { item: "Curry powder", amount: "2 tbsp" },
      { item: "Flatbread or pita", amount: "2" },
      { item: "Red onion (sliced)", amount: "1" },
      { item: "Cucumber (diced)", amount: "1/2" },
      { item: "Tomato (diced)", amount: "1" },
    ],
    instructions: [
      "Marinate chicken thighs in Greek yogurt and curry powder for at least 30 minutes.",
      "Grill or pan-fry chicken until golden and cooked through, about 8 minutes per side.",
      "Warm flatbreads in a dry pan.",
      "Slice chicken and assemble gyros with onion, cucumber, and tomato.",
      "Top with extra yogurt if desired.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "naked-chicken-burrito-bowl",
    name: "Naked Chicken Burrito Bowl",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/naked-chicken-burrito-bowl-meal-prep/",
    image: "/images/recipes/naked-chicken-burrito-bowl.png",
    calories: 278, protein: 30, carbs: 35, fat: 8, servings: 1,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "Chicken breast", amount: "150g" },
      { item: "Brown rice (cooked)", amount: "100g" },
      { item: "Black beans (drained)", amount: "60g" },
      { item: "Corn kernels", amount: "40g" },
      { item: "Salsa", amount: "2 tbsp" },
      { item: "Lime juice", amount: "1 tbsp" },
      { item: "Cumin", amount: "1 tsp" },
    ],
    instructions: [
      "Season chicken with cumin, salt, and pepper. Grill until cooked through.",
      "Slice chicken and arrange over brown rice.",
      "Top with black beans, corn, and salsa.",
      "Squeeze lime juice over the bowl and serve.",
    ],
    tags: ["high-protein", "low-fat", "meal-prep"],
  },
  {
    id: "chicken-tikka-masala",
    name: "30-Minute Chicken Tikka Masala",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/30-minute-chicken-tikka-masala-meal-prep/",
    image: "/images/recipes/chicken-tikka-masala.png",
    calories: 586, protein: 49, carbs: 69, fat: 14, servings: 4,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Chicken breast (diced)", amount: "600g" },
      { item: "Tikka masala paste", amount: "4 tbsp" },
      { item: "Chopped tomatoes (canned)", amount: "400g" },
      { item: "Greek yogurt", amount: "100g" },
      { item: "Basmati rice", amount: "300g" },
      { item: "Onion (diced)", amount: "1" },
      { item: "Garlic (minced)", amount: "3 cloves" },
      { item: "Ginger (grated)", amount: "1 tbsp" },
    ],
    instructions: [
      "Sauté onion, garlic, and ginger in a large pan until softened.",
      "Add tikka masala paste and cook for 1 minute.",
      "Add chicken and cook until sealed on all sides.",
      "Pour in chopped tomatoes, simmer for 15 minutes until chicken is cooked.",
      "Stir in Greek yogurt and season to taste.",
      "Cook basmati rice according to package directions. Serve alongside.",
    ],
    tags: ["high-protein", "meal-prep", "batch-cook"],
  },
  {
    id: "bbq-chicken-rice",
    name: "BBQ Chicken & Rice",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/meal-prep-chicken-and-rice-recipe/",
    image: "/images/recipes/bbq-chicken-rice.png",
    calories: 511, protein: 41, carbs: 57, fat: 6, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "Chicken breast", amount: "600g" },
      { item: "BBQ sauce (low sugar)", amount: "4 tbsp" },
      { item: "Basmati rice", amount: "300g" },
      { item: "Broccoli", amount: "200g" },
      { item: "Red bell pepper", amount: "1" },
    ],
    instructions: [
      "Preheat oven to 200°C (400°F). Place chicken on a baking tray.",
      "Brush chicken with BBQ sauce and bake for 20-25 minutes.",
      "Cook rice according to package directions. Steam broccoli and slice pepper.",
      "Slice chicken and divide among meal prep containers with rice and vegetables.",
    ],
    tags: ["high-protein", "low-fat", "meal-prep", "batch-cook"],
  },
  {
    id: "one-pot-garlic-chicken-rice",
    name: "One-Pot Creamy Garlic Chicken & Rice",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/one-pot-creamy-garlic-chicken-rice/",
    image: "/images/recipes/one-pot-garlic-chicken-rice.png",
    calories: 387, protein: 45, carbs: 32, fat: 7, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "Chicken breast (diced)", amount: "600g" },
      { item: "Garlic (minced)", amount: "4 cloves" },
      { item: "Long grain rice", amount: "250g" },
      { item: "Chicken stock", amount: "500ml" },
      { item: "Light cream cheese", amount: "2 tbsp" },
      { item: "Spinach", amount: "100g" },
      { item: "Onion (diced)", amount: "1" },
    ],
    instructions: [
      "Sauté diced chicken in a large pot until sealed. Remove and set aside.",
      "Cook onion and garlic until softened. Add rice and stir to coat.",
      "Pour in chicken stock, bring to a boil, then reduce heat and simmer 15 minutes.",
      "Return chicken to the pot. Stir in cream cheese and spinach until wilted.",
      "Season to taste and divide among containers.",
    ],
    tags: ["high-protein", "low-fat", "meal-prep", "one-pot"],
  },

  // ── Fish ────────────────────────────────────────────────────────────────────
  {
    id: "easy-tuna-pasta-salad",
    name: "Easy Tuna Pasta Salad",
    category: "Fish",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/easy-pasta-salad-meal-prep-recipe/",
    image: "/images/recipes/easy-tuna-pasta-salad.png",
    calories: 415, protein: 26, carbs: 40, fat: 20, servings: 2,
    prepTime: 10, cookTime: 10,
    ingredients: [
      { item: "Pasta (fusilli or penne)", amount: "200g" },
      { item: "Canned tuna (drained)", amount: "160g" },
      { item: "Sweetcorn", amount: "80g" },
      { item: "Red onion (diced)", amount: "1/2" },
      { item: "Mayonnaise (light)", amount: "2 tbsp" },
      { item: "Lemon juice", amount: "1 tbsp" },
    ],
    instructions: [
      "Cook pasta according to package directions. Drain and cool under cold water.",
      "Flake tuna into a large bowl.",
      "Add sweetcorn, red onion, mayonnaise, and lemon juice. Mix well.",
      "Fold in cooled pasta and season to taste.",
    ],
    tags: ["high-protein", "meal-prep", "quick", "no-cook"],
  },

  // ── Beef ────────────────────────────────────────────────────────────────────
  {
    id: "hp-buffalo-mac-cheese",
    name: "High-Protein Buffalo Mac and Cheese",
    category: "Beef",
    source: "Jenneatsgoood",
    calories: 520, protein: 48, carbs: 45, fat: 16, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "High-protein pasta", amount: "340g" },
      { item: "Chicken breast (shredded)", amount: "450g" },
      { item: "Buffalo sauce", amount: "60ml" },
      { item: "Cottage cheese (blended)", amount: "230g" },
      { item: "Sharp cheddar (shredded)", amount: "115g" },
      { item: "Cauliflower (riced)", amount: "150g" },
      { item: "Garlic powder", amount: "1 tsp" },
    ],
    instructions: [
      "Cook pasta according to package directions. Reserve 1/2 cup pasta water.",
      "Blend cottage cheese until smooth to create the sauce base.",
      "In a large skillet, combine shredded chicken with buffalo sauce and warm through.",
      "Add blended cottage cheese, shredded cheddar, and riced cauliflower to the skillet.",
      "Fold in cooked pasta, adding pasta water as needed for creaminess.",
      "Season with garlic powder, salt, and pepper.",
    ],
    tags: ["high-protein", "meal-prep", "comfort-food"],
  },
  {
    id: "spiced-chicken-sausage-rice",
    name: "One-Pot Spiced Chicken Sausage and Rice",
    category: "Poultry",
    source: "Jenneatsgoood",
    calories: 480, protein: 53, carbs: 42, fat: 10, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "Chicken sausage links", amount: "450g" },
      { item: "Basmati rice", amount: "250g" },
      { item: "Bone broth", amount: "500ml" },
      { item: "Diced tomatoes (canned)", amount: "400g" },
      { item: "Onion (diced)", amount: "1" },
      { item: "Bell pepper (diced)", amount: "1" },
      { item: "Smoked paprika", amount: "1 tbsp" },
      { item: "Cumin", amount: "1 tsp" },
    ],
    instructions: [
      "Slice chicken sausages and brown in a large pot.",
      "Add onion and bell pepper, cook until softened.",
      "Stir in rice, paprika, and cumin. Toast for 1 minute.",
      "Add bone broth and diced tomatoes. Bring to a boil.",
      "Cover, reduce heat, and simmer for 18-20 minutes until rice is cooked.",
      "Fluff with a fork and season to taste.",
    ],
    tags: ["high-protein", "meal-prep", "one-pot", "batch-cook"],
  },
  {
    id: "spicy-beef-mac-cheese",
    name: "High-Protein Spicy Beef Mac and Cheese",
    category: "Beef",
    source: "Jenneatsgoood",
    calories: 550, protein: 50, carbs: 48, fat: 15, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "High-protein pasta", amount: "340g" },
      { item: "Ground beef (90/10)", amount: "450g" },
      { item: "Cottage cheese (blended)", amount: "230g" },
      { item: "Pepper jack cheese (shredded)", amount: "115g" },
      { item: "Zucchini (diced small)", amount: "150g" },
      { item: "Jalapeño (diced)", amount: "1" },
      { item: "Chili powder", amount: "1 tsp" },
    ],
    instructions: [
      "Cook pasta according to package directions. Reserve pasta water.",
      "Brown ground beef in a large skillet, breaking into crumbles. Drain excess fat.",
      "Add diced zucchini and jalapeño, cook 3-4 minutes.",
      "Blend cottage cheese smooth, add to skillet with pepper jack.",
      "Fold in cooked pasta and chili powder. Add pasta water for consistency.",
      "Season and divide among meal prep containers.",
    ],
    tags: ["high-protein", "meal-prep", "comfort-food"],
  },
  {
    id: "beef-egg-roll-bowl",
    name: "Beef Egg Roll in a Bowl with Bone Broth Rice",
    category: "Beef",
    source: "Jenneatsgoood",
    calories: 420, protein: 33, carbs: 38, fat: 14, servings: 4,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Ground beef (90/10)", amount: "450g" },
      { item: "Coleslaw mix (shredded cabbage)", amount: "400g" },
      { item: "Soy sauce", amount: "3 tbsp" },
      { item: "Sesame oil", amount: "1 tbsp" },
      { item: "Rice vinegar", amount: "1 tbsp" },
      { item: "Garlic (minced)", amount: "3 cloves" },
      { item: "Ginger (grated)", amount: "1 tsp" },
      { item: "Jasmine rice", amount: "250g" },
      { item: "Bone broth", amount: "500ml" },
    ],
    instructions: [
      "Cook rice in bone broth instead of water for extra protein.",
      "Brown ground beef in a large skillet. Add garlic and ginger, cook 1 minute.",
      "Add coleslaw mix and cook until wilted, about 4-5 minutes.",
      "Stir in soy sauce, sesame oil, and rice vinegar.",
      "Serve over bone broth rice. Garnish with green onions and sesame seeds.",
    ],
    tags: ["high-protein", "meal-prep", "quick"],
  },

  // ── Breakfast ──────────────────────────────────────────────────────────────
  {
    id: "hp-breakfast-burrito",
    name: "High-Protein Breakfast Burrito",
    category: "Breakfast",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/high-protein-breakfast-burritos",
    image: "/images/recipes/hp-breakfast-burrito.png",
    calories: 480, protein: 38, carbs: 36, fat: 20, servings: 2,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "Whole eggs", amount: "4" },
      { item: "Egg whites", amount: "4" },
      { item: "Turkey sausage", amount: "115g" },
      { item: "Black beans (drained)", amount: "80g" },
      { item: "Cheddar cheese (shredded)", amount: "60g" },
      { item: "Flour tortilla (large)", amount: "2" },
      { item: "Salsa", amount: "4 tbsp" },
    ],
    instructions: [
      "Cook turkey sausage in a skillet, breaking into crumbles.",
      "Whisk eggs and egg whites. Scramble in the same skillet with sausage.",
      "Warm tortillas in a dry pan or microwave.",
      "Fill tortillas with egg mixture, black beans, cheese, and salsa.",
      "Roll into burritos. Wrap in foil for meal prep storage.",
    ],
    tags: ["high-protein", "meal-prep", "quick"],
  },
  {
    id: "cheeseburger-omelette",
    name: "High-Protein Cheeseburger Omelette",
    category: "Breakfast",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/high-protein-cheeseburger-omelette",
    image: "/images/recipes/cheeseburger-omelette.png",
    calories: 390, protein: 42, carbs: 5, fat: 22, servings: 1,
    prepTime: 5, cookTime: 10,
    ingredients: [
      { item: "Whole eggs", amount: "3" },
      { item: "Ground beef (lean)", amount: "85g" },
      { item: "American cheese", amount: "1 slice" },
      { item: "Onion (diced)", amount: "2 tbsp" },
      { item: "Tomato (diced)", amount: "2 tbsp" },
      { item: "Pickles (diced)", amount: "1 tbsp" },
      { item: "Mustard", amount: "1 tsp" },
    ],
    instructions: [
      "Brown ground beef with diced onion in a small skillet. Season with salt and pepper.",
      "Beat eggs and pour into a separate oiled pan over medium heat.",
      "When eggs are nearly set, add beef mixture and cheese to one half.",
      "Fold omelette over and cook 1 more minute.",
      "Top with diced tomato, pickles, and mustard.",
    ],
    tags: ["high-protein", "low-carb", "quick"],
  },

  // ── Vegetarian ─────────────────────────────────────────────────────────────
  {
    id: "pineapple-glazed-chicken-bowls",
    name: "Sweet Pineapple Glazed Chicken Bowls",
    category: "Poultry",
    source: "Jenneatsgoood",
    calories: 450, protein: 45, carbs: 48, fat: 8, servings: 4,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Chicken breast", amount: "600g" },
      { item: "Pineapple juice", amount: "120ml" },
      { item: "Soy sauce", amount: "2 tbsp" },
      { item: "Honey", amount: "1 tbsp" },
      { item: "Rice vinegar", amount: "1 tbsp" },
      { item: "Jasmine rice", amount: "250g" },
      { item: "Cauliflower rice", amount: "200g" },
      { item: "Bone broth", amount: "500ml" },
    ],
    instructions: [
      "Cook jasmine rice in bone broth. Mix with cauliflower rice for extra volume.",
      "Whisk pineapple juice, soy sauce, honey, and rice vinegar for glaze.",
      "Cut chicken into strips. Sear in a hot skillet until golden.",
      "Pour glaze over chicken and cook until thickened and chicken is cooked through.",
      "Serve chicken over rice blend. Top with green onions and sesame seeds.",
    ],
    tags: ["high-protein", "meal-prep", "sweet-savory"],
  },

  // ── Sweet ──────────────────────────────────────────────────────────────────
  {
    id: "lean-beef-enchiladas",
    name: "Lean Beef Enchiladas",
    category: "Beef",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/bodybuilders-lean-beef-enchiladas",
    image: "/images/recipes/lean-beef-enchiladas.png",
    calories: 380, protein: 32, carbs: 30, fat: 14, servings: 4,
    prepTime: 15, cookTime: 25,
    ingredients: [
      { item: "Ground beef (93/7)", amount: "450g" },
      { item: "Low-carb tortillas", amount: "8" },
      { item: "Enchilada sauce", amount: "400ml" },
      { item: "Black beans (drained)", amount: "200g" },
      { item: "Mexican cheese blend", amount: "115g" },
      { item: "Onion (diced)", amount: "1" },
      { item: "Cumin", amount: "1 tsp" },
    ],
    instructions: [
      "Preheat oven to 190°C (375°F).",
      "Brown ground beef with onion and cumin. Stir in black beans.",
      "Spread a thin layer of enchilada sauce on the bottom of a baking dish.",
      "Fill tortillas with beef mixture, roll up, and place seam-side down.",
      "Pour remaining enchilada sauce over top. Sprinkle with cheese.",
      "Bake 20-25 minutes until bubbly and cheese is melted.",
    ],
    tags: ["high-protein", "meal-prep", "batch-cook"],
  },

  // ── Poultry (continued from MyProtein) ─────────────────────────────────────
  {
    id: "creamy-lemon-thyme-chicken",
    name: "Creamy Lemon & Thyme Chicken",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/creamy-lemon-thyme-chicken/",
    image: "/images/recipes/creamy-lemon-thyme-chicken.png",
    calories: 227, protein: 21, carbs: 5, fat: 14, servings: 4,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Chicken thigh (boneless)", amount: "500g" },
      { item: "Lemon (juice + zest)", amount: "1" },
      { item: "Fresh thyme", amount: "2 tbsp" },
      { item: "Cream cheese (light)", amount: "60g" },
      { item: "Chicken stock", amount: "100ml" },
      { item: "Garlic (minced)", amount: "2 cloves" },
    ],
    instructions: [
      "Season chicken thighs with salt, pepper, and thyme.",
      "Sear chicken in a hot pan until golden, about 4 minutes per side.",
      "Add garlic and cook 30 seconds. Pour in chicken stock and lemon juice.",
      "Simmer 10 minutes until chicken is cooked through.",
      "Stir in cream cheese and lemon zest until sauce is creamy.",
    ],
    tags: ["low-carb", "quick"],
  },
  {
    id: "creamy-cajun-chicken-pasta",
    name: "Creamy Cajun Chicken Pasta",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/creamy-cajun-chicken-pasta-high-protein-meal-prep/",
    image: "/images/recipes/creamy-cajun-chicken-pasta.png",
    calories: 516, protein: 38, carbs: 71, fat: 8, servings: 4,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Chicken breast (diced)", amount: "500g" },
      { item: "Penne pasta", amount: "350g" },
      { item: "Cajun seasoning", amount: "2 tbsp" },
      { item: "Light cream cheese", amount: "100g" },
      { item: "Bell peppers (mixed, sliced)", amount: "2" },
      { item: "Onion (sliced)", amount: "1" },
    ],
    instructions: [
      "Cook pasta according to package directions.",
      "Season chicken with Cajun seasoning. Pan-fry until golden and cooked through.",
      "Sauté peppers and onion until softened.",
      "Stir in cream cheese with a splash of pasta water to create sauce.",
      "Toss pasta with chicken, vegetables, and sauce.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "buffalo-chicken-pasta-salad",
    name: "Buffalo Chicken Pasta Salad",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/buffalo-chicken-3-day-chicken-meal-prep/",
    image: "/images/recipes/buffalo-chicken-pasta-salad.png",
    calories: 485, protein: 49, carbs: 30, fat: 20, servings: 3,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Chicken breast", amount: "450g" },
      { item: "Pasta (fusilli)", amount: "200g" },
      { item: "Buffalo sauce", amount: "60ml" },
      { item: "Greek yogurt", amount: "60g" },
      { item: "Celery (diced)", amount: "2 stalks" },
      { item: "Red onion (diced)", amount: "1/2" },
    ],
    instructions: [
      "Cook and shred chicken breast. Toss with buffalo sauce.",
      "Cook pasta and cool under cold water.",
      "Mix Greek yogurt with a splash of buffalo sauce for dressing.",
      "Combine pasta, chicken, celery, and onion. Toss with dressing.",
    ],
    tags: ["high-protein", "meal-prep", "no-cook"],
  },
  {
    id: "zingy-chicken-burger",
    name: "Zingy Chicken Burger",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/zingy-chicken-burger-fakeaway-recipes/",
    image: "/images/recipes/zingy-chicken-burger.png",
    calories: 468, protein: 59, carbs: 49, fat: 12, servings: 2,
    prepTime: 15, cookTime: 15,
    ingredients: [
      { item: "Chicken breast", amount: "300g" },
      { item: "Burger buns (wholemeal)", amount: "2" },
      { item: "Cornflake crumbs", amount: "40g" },
      { item: "Egg white", amount: "1" },
      { item: "Lettuce", amount: "handful" },
      { item: "Sriracha mayo (light)", amount: "2 tbsp" },
    ],
    instructions: [
      "Butterfly chicken breasts to even thickness.",
      "Dip in egg white, then coat in cornflake crumbs.",
      "Bake at 200°C for 15 minutes until crispy and cooked through.",
      "Assemble burgers with lettuce and sriracha mayo.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "easy-pesto-chicken-veg",
    name: "Easy Pesto Chicken & Veg",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/easy-pesto-chicken-veg-meal-prep/",
    image: "/images/recipes/easy-pesto-chicken-veg.png",
    calories: 523, protein: 52, carbs: 36, fat: 16, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "Chicken breast", amount: "600g" },
      { item: "Green pesto", amount: "4 tbsp" },
      { item: "New potatoes", amount: "400g" },
      { item: "Cherry tomatoes", amount: "200g" },
      { item: "Green beans", amount: "200g" },
    ],
    instructions: [
      "Preheat oven to 200°C. Halve potatoes and par-boil 10 minutes.",
      "Coat chicken in pesto. Place on a baking tray with potatoes and tomatoes.",
      "Bake 20-25 minutes until chicken is cooked.",
      "Steam green beans. Serve alongside chicken and potatoes.",
    ],
    tags: ["high-protein", "meal-prep", "one-tray"],
  },
  {
    id: "fajita-pasta-bake",
    name: "Fajita Pasta Bake",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/fajita-pasta-bake-2/",
    image: "/images/recipes/fajita-pasta-bake.png",
    calories: 521, protein: 28, carbs: 62, fat: 16, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "Chicken breast (diced)", amount: "400g" },
      { item: "Penne pasta", amount: "300g" },
      { item: "Fajita seasoning", amount: "2 tbsp" },
      { item: "Passata", amount: "400g" },
      { item: "Bell peppers (mixed)", amount: "2" },
      { item: "Cheddar cheese", amount: "80g" },
    ],
    instructions: [
      "Cook pasta. Season and pan-fry diced chicken with peppers.",
      "Combine chicken, pasta, passata, and fajita seasoning in a baking dish.",
      "Top with grated cheddar and bake at 200°C for 15-20 minutes until bubbly.",
    ],
    tags: ["meal-prep", "batch-cook", "comfort-food"],
  },
  {
    id: "chicken-chorizo-paella",
    name: "Chicken & Chorizo Paella",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/chicken-chorizo-paella/",
    image: "/images/recipes/chicken-chorizo-paella.png",
    calories: 404, protein: 31, carbs: 52, fat: 7, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "Chicken thigh (diced)", amount: "400g" },
      { item: "Chorizo (sliced)", amount: "60g" },
      { item: "Paella rice", amount: "300g" },
      { item: "Chicken stock", amount: "600ml" },
      { item: "Smoked paprika", amount: "1 tbsp" },
      { item: "Peas (frozen)", amount: "100g" },
    ],
    instructions: [
      "Fry chorizo until crispy. Add chicken and cook until sealed.",
      "Stir in rice and paprika. Toast for 1 minute.",
      "Pour in stock, bring to a boil. Simmer 18-20 minutes.",
      "Add peas in the last 3 minutes. Rest 5 minutes before serving.",
    ],
    tags: ["high-protein", "one-pot", "meal-prep"],
  },
  {
    id: "easy-protein-bowl",
    name: "Easy Protein Bowl",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/easy-protein-bowl-meal-prep/",
    image: "/images/recipes/easy-protein-bowl.png",
    calories: 620, protein: 55, carbs: 87, fat: 10, servings: 1,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "Chicken breast", amount: "200g" },
      { item: "Brown rice (cooked)", amount: "200g" },
      { item: "Sweetcorn", amount: "60g" },
      { item: "Edamame beans", amount: "50g" },
      { item: "Soy sauce", amount: "1 tbsp" },
      { item: "Sesame seeds", amount: "1 tsp" },
    ],
    instructions: [
      "Grill chicken breast, seasoned with soy sauce.",
      "Arrange rice in a bowl. Top with sliced chicken, corn, and edamame.",
      "Drizzle with soy sauce and sprinkle sesame seeds.",
    ],
    tags: ["high-protein", "meal-prep", "quick"],
  },
  {
    id: "marry-me-chicken-pasta",
    name: "Marry Me Chicken Pasta",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/marry-me-chicken/",
    image: "/images/recipes/marry-me-chicken-pasta.png",
    calories: 460, protein: 36, carbs: 52, fat: 13, servings: 4,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Chicken breast", amount: "500g" },
      { item: "Penne pasta", amount: "300g" },
      { item: "Sun-dried tomatoes", amount: "50g" },
      { item: "Light cream cheese", amount: "100g" },
      { item: "Chicken stock", amount: "200ml" },
      { item: "Garlic (minced)", amount: "3 cloves" },
      { item: "Italian seasoning", amount: "1 tbsp" },
    ],
    instructions: [
      "Season and sear chicken until golden. Set aside.",
      "Sauté garlic, add stock, sun-dried tomatoes, and Italian seasoning.",
      "Stir in cream cheese to make sauce. Slice and return chicken.",
      "Cook pasta and toss with sauce.",
    ],
    tags: ["meal-prep", "comfort-food"],
  },
  {
    id: "one-pot-chicken-ramen",
    name: "Easy One-Pot Chicken Ramen",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/easy-one-pot-chicken-ramen/",
    image: "/images/recipes/one-pot-chicken-ramen.png",
    calories: 479, protein: 47, carbs: 35, fat: 11, servings: 2,
    prepTime: 5, cookTime: 15,
    ingredients: [
      { item: "Chicken breast (sliced thin)", amount: "300g" },
      { item: "Ramen noodles", amount: "150g" },
      { item: "Chicken stock", amount: "600ml" },
      { item: "Soy sauce", amount: "2 tbsp" },
      { item: "Ginger (grated)", amount: "1 tbsp" },
      { item: "Soft-boiled egg", amount: "2" },
      { item: "Spring onions", amount: "2" },
    ],
    instructions: [
      "Bring stock to a boil with soy sauce and ginger.",
      "Add chicken slices and cook 5 minutes.",
      "Add noodles and cook according to package time.",
      "Serve in bowls topped with soft-boiled egg and spring onions.",
    ],
    tags: ["high-protein", "quick", "one-pot"],
  },
  {
    id: "creamy-tomato-chicken-sandwich",
    name: "Creamy Tomato Chicken Sandwich",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/creamy-tomato-chicken-sandwich-protein-plates-recipe-book/",
    image: "/images/recipes/creamy-tomato-chicken-sandwich.png",
    calories: 359, protein: 29, carbs: 32, fat: 11, servings: 2,
    prepTime: 10, cookTime: 10,
    ingredients: [
      { item: "Cooked chicken (shredded)", amount: "200g" },
      { item: "Bread slices", amount: "4" },
      { item: "Sun-dried tomato paste", amount: "2 tbsp" },
      { item: "Light cream cheese", amount: "2 tbsp" },
      { item: "Rocket leaves", amount: "handful" },
    ],
    instructions: [
      "Mix cream cheese with sun-dried tomato paste.",
      "Spread on bread. Layer with shredded chicken and rocket.",
      "Close sandwiches. Wrap for meal prep.",
    ],
    tags: ["quick", "no-cook", "meal-prep"],
  },
  {
    id: "crispy-honey-sriracha-tenders",
    name: "Crispy Honey Sriracha Chicken Tenders",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/honey-sriracha-chicken-tenders/",
    image: "/images/recipes/crispy-honey-sriracha-tenders.png",
    calories: 335, protein: 40, carbs: 37, fat: 2, servings: 2,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Chicken breast (strips)", amount: "300g" },
      { item: "Panko breadcrumbs", amount: "60g" },
      { item: "Egg white", amount: "1" },
      { item: "Honey", amount: "2 tbsp" },
      { item: "Sriracha", amount: "1 tbsp" },
    ],
    instructions: [
      "Dip chicken strips in egg white, then coat in panko.",
      "Bake at 200°C for 18-20 minutes until crispy.",
      "Mix honey and sriracha. Drizzle over tenders.",
    ],
    tags: ["high-protein", "low-fat"],
  },
  {
    id: "peri-peri-chicken",
    name: "Peri Peri Chicken",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/peri-peri-chicken-fakeaway/",
    image: "/images/recipes/peri-peri-chicken.png",
    calories: 656, protein: 42, carbs: 67, fat: 26, servings: 2,
    prepTime: 15, cookTime: 25,
    ingredients: [
      { item: "Chicken thighs (bone-in)", amount: "4" },
      { item: "Peri peri sauce", amount: "4 tbsp" },
      { item: "Rice", amount: "200g" },
      { item: "Corn on the cob", amount: "2" },
      { item: "Coleslaw", amount: "100g" },
    ],
    instructions: [
      "Marinate chicken in peri peri sauce for at least 1 hour.",
      "Bake at 200°C for 25 minutes until charred and cooked through.",
      "Cook rice and corn. Serve with coleslaw on the side.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "chicken-bacon-bulking-salad",
    name: "Chicken & Bacon Bulking Salad",
    category: "Poultry",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/chicken-bacon-bulking-salad-high-protein-1350kcal/",
    image: "/images/recipes/chicken-bacon-bulking-salad.png",
    calories: 1361, protein: 95, carbs: 27, fat: 99, servings: 1,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "Chicken breast (grilled)", amount: "250g" },
      { item: "Bacon rashers", amount: "4" },
      { item: "Avocado", amount: "1" },
      { item: "Mixed salad leaves", amount: "100g" },
      { item: "Cherry tomatoes", amount: "100g" },
      { item: "Olive oil dressing", amount: "2 tbsp" },
    ],
    instructions: [
      "Grill chicken and bacon until cooked.",
      "Arrange salad leaves on a plate. Top with sliced chicken, bacon, and avocado.",
      "Add tomatoes and drizzle with dressing.",
    ],
    tags: ["high-protein", "bulking", "high-calorie"],
  },

  // ── Fish (continued) ───────────────────────────────────────────────────────
  {
    id: "salmon-poke-bowl",
    name: "Salmon Poke Bowl",
    category: "Fish",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/salmon-poke-bowl-recipe-high-protein-meal-prep/",
    image: "/images/recipes/salmon-poke-bowl.png",
    calories: 552, protein: 24, carbs: 70, fat: 19, servings: 2,
    prepTime: 15, cookTime: 5,
    ingredients: [
      { item: "Salmon fillet (sushi-grade)", amount: "200g" },
      { item: "Sushi rice (cooked)", amount: "300g" },
      { item: "Soy sauce", amount: "2 tbsp" },
      { item: "Sesame oil", amount: "1 tsp" },
      { item: "Cucumber (sliced)", amount: "1/2" },
      { item: "Avocado (sliced)", amount: "1/2" },
      { item: "Edamame", amount: "50g" },
    ],
    instructions: [
      "Dice salmon into cubes. Marinate in soy sauce and sesame oil.",
      "Divide rice between bowls.",
      "Top with salmon, cucumber, avocado, and edamame.",
      "Garnish with sesame seeds and spring onions.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "sweet-chilli-glazed-salmon",
    name: "Sweet Chilli Glazed Salmon",
    category: "Fish",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/sweet-chilli-glazed-salmon/",
    image: "/images/recipes/sweet-chilli-glazed-salmon.png",
    calories: 483, protein: 29, carbs: 54, fat: 16, servings: 2,
    prepTime: 5, cookTime: 15,
    ingredients: [
      { item: "Salmon fillets", amount: "2" },
      { item: "Sweet chilli sauce", amount: "3 tbsp" },
      { item: "Rice noodles", amount: "150g" },
      { item: "Pak choi", amount: "2 heads" },
      { item: "Soy sauce", amount: "1 tbsp" },
    ],
    instructions: [
      "Brush salmon with sweet chilli sauce.",
      "Bake at 200°C for 12-15 minutes.",
      "Cook rice noodles. Stir-fry pak choi with soy sauce.",
      "Serve salmon over noodles with pak choi.",
    ],
    tags: ["quick", "meal-prep"],
  },
  {
    id: "homemade-fish-finger-sandwich",
    name: "Homemade Fish Finger Sandwich",
    category: "Fish",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/homemade-fish-finger-sandwich-protein-plates-recipe-book/",
    image: "/images/recipes/homemade-fish-finger-sandwich.png",
    calories: 685, protein: 38, carbs: 86, fat: 20, servings: 2,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "White fish fillets (cod)", amount: "300g" },
      { item: "Panko breadcrumbs", amount: "80g" },
      { item: "Egg", amount: "1" },
      { item: "Flour", amount: "30g" },
      { item: "Bread rolls", amount: "2" },
      { item: "Tartare sauce", amount: "2 tbsp" },
      { item: "Lettuce", amount: "handful" },
    ],
    instructions: [
      "Cut fish into fingers. Coat in flour, then egg, then panko.",
      "Bake at 200°C for 12-15 minutes until golden and crispy.",
      "Assemble in bread rolls with tartare sauce and lettuce.",
    ],
    tags: ["meal-prep", "comfort-food"],
  },
  {
    id: "crispy-sriracha-prawn-black-rice",
    name: "Crispy Sriracha Prawns with Black Rice",
    category: "Fish",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/crispy-sriracha-prawns-with-black-rice/",
    image: "/images/recipes/crispy-sriracha-prawn-black-rice.png",
    calories: 520, protein: 49, carbs: 72, fat: 15, servings: 2,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "King prawns", amount: "300g" },
      { item: "Sriracha sauce", amount: "2 tbsp" },
      { item: "Black rice (cooked)", amount: "250g" },
      { item: "Cornflour", amount: "2 tbsp" },
      { item: "Sesame oil", amount: "1 tbsp" },
      { item: "Spring onions", amount: "2" },
    ],
    instructions: [
      "Coat prawns in cornflour. Fry in sesame oil until crispy.",
      "Toss prawns in sriracha sauce.",
      "Serve over black rice. Garnish with spring onions.",
    ],
    tags: ["high-protein", "quick"],
  },

  // ── Beef (continued from MyProtein) ────────────────────────────────────────
  {
    id: "low-carb-loaf-tin-lasagne",
    name: "Low-Carb Loaf Tin Lasagne",
    category: "Beef",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/loaf-tin-lasagne-3-day-meal-prep/",
    image: "/images/recipes/low-carb-loaf-tin-lasagne.png",
    calories: 527, protein: 36, carbs: 68, fat: 22, servings: 4,
    prepTime: 15, cookTime: 30,
    ingredients: [
      { item: "Lean ground beef", amount: "400g" },
      { item: "Lasagne sheets", amount: "6" },
      { item: "Passata", amount: "400g" },
      { item: "Béchamel sauce (light)", amount: "200ml" },
      { item: "Mozzarella (grated)", amount: "80g" },
      { item: "Onion (diced)", amount: "1" },
    ],
    instructions: [
      "Brown beef with onion. Add passata and simmer 10 minutes.",
      "Layer beef sauce, lasagne sheets, and béchamel in a loaf tin.",
      "Top with mozzarella. Bake at 190°C for 25-30 minutes.",
    ],
    tags: ["meal-prep", "batch-cook", "comfort-food"],
  },
  {
    id: "creamy-sausage-pasta",
    name: "Creamy Sausage Pasta",
    category: "Beef",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/healthy-pasta-recipes-sausage-pasta/",
    image: "/images/recipes/creamy-sausage-pasta.png",
    calories: 415, protein: 34, carbs: 48, fat: 5, servings: 4,
    prepTime: 5, cookTime: 20,
    ingredients: [
      { item: "Reduced-fat sausages", amount: "6" },
      { item: "Penne pasta", amount: "350g" },
      { item: "Quark", amount: "150g" },
      { item: "Passata", amount: "200g" },
      { item: "Garlic (minced)", amount: "2 cloves" },
      { item: "Italian seasoning", amount: "1 tsp" },
    ],
    instructions: [
      "Squeeze sausage meat from casings. Fry until browned.",
      "Cook pasta according to package directions.",
      "Add passata and garlic to sausage meat. Simmer 10 minutes.",
      "Stir in quark and Italian seasoning. Toss with pasta.",
    ],
    tags: ["high-protein", "low-fat", "meal-prep"],
  },
  {
    id: "beef-ramen-noodles",
    name: "Beef Ramen Noodles",
    category: "Beef",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/beef-ramen-noodles-high-protein/",
    image: "/images/recipes/beef-ramen-noodles.png",
    calories: 482, protein: 26, carbs: 61, fat: 15, servings: 2,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "Sirloin steak (sliced thin)", amount: "200g" },
      { item: "Ramen noodles", amount: "150g" },
      { item: "Beef stock", amount: "600ml" },
      { item: "Soy sauce", amount: "2 tbsp" },
      { item: "Pak choi", amount: "2 heads" },
      { item: "Soft-boiled egg", amount: "2" },
    ],
    instructions: [
      "Sear steak slices in a hot pan. Set aside.",
      "Bring stock to a boil with soy sauce. Add noodles and pak choi.",
      "Cook 3-4 minutes. Ladle into bowls.",
      "Top with steak and halved soft-boiled eggs.",
    ],
    tags: ["high-protein", "quick"],
  },
  {
    id: "homemade-beef-crunch-wraps",
    name: "Homemade Beef Crunch Wraps",
    category: "Beef",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/homemade-beef-crunch-wraps-fakeaway/",
    image: "/images/recipes/homemade-beef-crunch-wraps.png",
    calories: 467, protein: 32, carbs: 37, fat: 20, servings: 4,
    prepTime: 15, cookTime: 15,
    ingredients: [
      { item: "Ground beef (lean)", amount: "400g" },
      { item: "Large tortillas", amount: "4" },
      { item: "Tostadas (small)", amount: "4" },
      { item: "Cheddar cheese", amount: "80g" },
      { item: "Sour cream (light)", amount: "4 tbsp" },
      { item: "Taco seasoning", amount: "2 tbsp" },
      { item: "Lettuce (shredded)", amount: "100g" },
    ],
    instructions: [
      "Brown beef with taco seasoning.",
      "Layer beef, tostada, sour cream, cheese, and lettuce on tortilla.",
      "Fold tortilla into a hexagonal crunch wrap shape.",
      "Pan-fry seam-side down until golden on both sides.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "meatball-chilli-con-carne",
    name: "Meatball Chilli Con Carne",
    category: "Beef",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipes/meatball-chilli-con-carne/",
    image: "/images/recipes/meatball-chilli-con-carne.png",
    calories: 411, protein: 34, carbs: 28, fat: 15, servings: 4,
    prepTime: 15, cookTime: 25,
    ingredients: [
      { item: "Ground beef (lean)", amount: "400g" },
      { item: "Chopped tomatoes (canned)", amount: "400g" },
      { item: "Kidney beans (drained)", amount: "200g" },
      { item: "Chilli powder", amount: "1 tbsp" },
      { item: "Cumin", amount: "1 tsp" },
      { item: "Onion (diced)", amount: "1" },
      { item: "Garlic (minced)", amount: "2 cloves" },
    ],
    instructions: [
      "Form beef into small meatballs. Brown in a large pan.",
      "Sauté onion and garlic. Add tomatoes, beans, and spices.",
      "Return meatballs to the pan. Simmer 20 minutes.",
      "Serve with rice or wrap in tortillas.",
    ],
    tags: ["high-protein", "meal-prep", "batch-cook"],
  },
  {
    id: "spicy-korean-beef-wraps",
    name: "Spicy Korean Beef Wraps",
    category: "Beef",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/spicy-korean-beef-wraps/",
    image: "/images/recipes/spicy-korean-beef-wraps.png",
    calories: 750, protein: 70, carbs: 105, fat: 30, servings: 2,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "Beef sirloin (sliced)", amount: "400g" },
      { item: "Gochujang paste", amount: "2 tbsp" },
      { item: "Soy sauce", amount: "2 tbsp" },
      { item: "Rice", amount: "200g" },
      { item: "Tortilla wraps", amount: "2 large" },
      { item: "Pickled vegetables", amount: "100g" },
    ],
    instructions: [
      "Marinate beef in gochujang and soy sauce.",
      "Stir-fry beef over high heat until cooked.",
      "Cook rice. Assemble wraps with beef, rice, and pickled vegetables.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "homemade-smash-burgers",
    name: "Homemade Smash Burgers",
    category: "Beef",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/homemade-smash-burgers-fakeaway-recipe/",
    image: "/images/recipes/homemade-smash-burgers.png",
    calories: 590, protein: 44, carbs: 53, fat: 21, servings: 2,
    prepTime: 10, cookTime: 10,
    ingredients: [
      { item: "Ground beef (80/20)", amount: "300g" },
      { item: "Burger buns", amount: "2" },
      { item: "American cheese", amount: "4 slices" },
      { item: "Onion (diced)", amount: "1/2" },
      { item: "Pickles", amount: "4 slices" },
      { item: "Burger sauce", amount: "2 tbsp" },
    ],
    instructions: [
      "Divide beef into 4 balls. Smash flat on a hot griddle.",
      "Season with salt and pepper. Cook 2 minutes per side.",
      "Add cheese while still hot. Toast buns on the griddle.",
      "Stack two patties per bun with pickles and sauce.",
    ],
    tags: ["high-protein", "quick"],
  },

  // ── Breakfast (continued from MyProtein) ───────────────────────────────────
  {
    id: "sweet-potato-chorizo-hash",
    name: "Sweet Potato & Chorizo Hash",
    category: "Breakfast",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/sweet-potato-hash-recipe/",
    image: "/images/recipes/sweet-potato-chorizo-hash.png",
    calories: 437, protein: 24, carbs: 38, fat: 23, servings: 2,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Sweet potato (diced)", amount: "300g" },
      { item: "Chorizo (diced)", amount: "80g" },
      { item: "Eggs", amount: "2" },
      { item: "Red onion (diced)", amount: "1" },
      { item: "Paprika", amount: "1 tsp" },
    ],
    instructions: [
      "Par-boil sweet potato 5 minutes. Drain.",
      "Fry chorizo until crispy. Add sweet potato and onion.",
      "Cook until potato is golden, about 10 minutes.",
      "Make 2 wells. Crack in eggs and cover to cook 3-4 minutes.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "ms-chicken-burrito-bowl",
    name: "High-Protein Chicken Burrito Bowl",
    category: "Poultry",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/high-protein-chicken-burrito-bowl",
    calories: 510, protein: 42, carbs: 50, fat: 14, servings: 2,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "Chicken breast (seasoned)", amount: "300g" },
      { item: "Cilantro lime rice", amount: "200g" },
      { item: "Black beans (drained)", amount: "100g" },
      { item: "Guacamole", amount: "60g" },
      { item: "Salsa", amount: "60g" },
      { item: "Corn kernels", amount: "60g" },
    ],
    instructions: [
      "Season chicken with cumin and chili powder. Grill until cooked.",
      "Cook rice with lime juice and chopped cilantro.",
      "Slice chicken. Assemble bowls with rice, beans, corn, guacamole, and salsa.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "ms-steak-grilled-cheese",
    name: "Steak & Grilled Cheese Sandwich",
    category: "Beef",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/pepper-jack-steak-grilled-cheese",
    image: "/images/recipes/ms-steak-grilled-cheese.png",
    calories: 480, protein: 40, carbs: 30, fat: 22, servings: 1,
    prepTime: 5, cookTime: 10,
    ingredients: [
      { item: "Sirloin steak (sliced)", amount: "140g" },
      { item: "Sourdough bread", amount: "2 slices" },
      { item: "Pepper jack cheese", amount: "2 slices" },
      { item: "Butter", amount: "1 tsp" },
      { item: "Onion (caramelized)", amount: "2 tbsp" },
    ],
    instructions: [
      "Sear steak slices over high heat. Season with salt and pepper.",
      "Butter bread. Layer steak, cheese, and onion between slices.",
      "Grill on a pan until golden and cheese is melted, about 3 minutes per side.",
    ],
    tags: ["high-protein", "quick"],
  },
  {
    id: "ms-turkey-meatballs-peppers",
    name: "Turkey Meatballs with Green Peppers",
    category: "Poultry",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/crock-pot-turkey-meat-balls-green-pepper",
    image: "/images/recipes/ms-turkey-meatballs-peppers.png",
    calories: 443, protein: 50, carbs: 20, fat: 18, servings: 8,
    prepTime: 15, cookTime: 240,
    ingredients: [
      { item: "Ground turkey", amount: "900g" },
      { item: "Green bell peppers (diced)", amount: "3" },
      { item: "Marinara sauce", amount: "400g" },
      { item: "Breadcrumbs", amount: "60g" },
      { item: "Egg", amount: "1" },
      { item: "Italian seasoning", amount: "1 tbsp" },
    ],
    instructions: [
      "Mix turkey with breadcrumbs, egg, and seasoning. Form into meatballs.",
      "Place meatballs and diced peppers in a slow cooker.",
      "Pour marinara sauce over. Cook on low 4 hours.",
    ],
    tags: ["high-protein", "meal-prep", "batch-cook", "slow-cooker"],
  },
  {
    id: "ms-chipotle-salmon",
    name: "Grilled Chipotle Salmon with Mango Salsa",
    category: "Fish",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/grilled-chipotle-salmon",
    image: "/images/recipes/ms-chipotle-salmon.png",
    calories: 420, protein: 35, carbs: 30, fat: 18, servings: 2,
    prepTime: 15, cookTime: 12,
    ingredients: [
      { item: "Salmon fillets", amount: "2" },
      { item: "Chipotle in adobo (minced)", amount: "1 tbsp" },
      { item: "Mango (diced)", amount: "1" },
      { item: "Black beans (drained)", amount: "100g" },
      { item: "Red onion (diced)", amount: "1/4" },
      { item: "Cilantro (chopped)", amount: "2 tbsp" },
      { item: "Lime juice", amount: "1 tbsp" },
    ],
    instructions: [
      "Rub salmon with chipotle. Grill 5-6 minutes per side.",
      "Combine mango, black beans, onion, cilantro, and lime juice for salsa.",
      "Serve salmon topped with mango salsa.",
    ],
    tags: ["high-protein", "quick"],
  },
  {
    id: "ms-buffalo-chicken-sliders",
    name: "Buffalo Chicken Sliders",
    category: "Poultry",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/gameday-buffalo-chicken-sliders",
    image: "/images/recipes/ms-buffalo-chicken-sliders.png",
    calories: 320, protein: 28, carbs: 24, fat: 12, servings: 4,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "Chicken breast (shredded)", amount: "400g" },
      { item: "Buffalo sauce", amount: "60ml" },
      { item: "Slider buns", amount: "8" },
      { item: "Blue cheese crumbles", amount: "40g" },
      { item: "Celery (diced)", amount: "2 stalks" },
    ],
    instructions: [
      "Shred cooked chicken and toss with buffalo sauce.",
      "Divide among slider buns. Top with blue cheese and celery.",
    ],
    tags: ["high-protein", "quick"],
  },
  {
    id: "ms-meatball-sub",
    name: "High-Protein Cheesy Meatball Sub",
    category: "Beef",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/high-protein-cheesy-meatball-sub",
    image: "/images/recipes/ms-meatball-sub.png",
    calories: 450, protein: 38, carbs: 35, fat: 18, servings: 2,
    prepTime: 15, cookTime: 20,
    ingredients: [
      { item: "Ground beef (lean)", amount: "300g" },
      { item: "Sub rolls", amount: "2" },
      { item: "Marinara sauce", amount: "200g" },
      { item: "Mozzarella cheese", amount: "60g" },
      { item: "Italian seasoning", amount: "1 tsp" },
      { item: "Garlic powder", amount: "1/2 tsp" },
    ],
    instructions: [
      "Mix beef with Italian seasoning and garlic. Form into meatballs.",
      "Brown meatballs in a pan. Add marinara and simmer 10 minutes.",
      "Fill sub rolls. Top with mozzarella and broil until melted.",
    ],
    tags: ["high-protein", "comfort-food"],
  },
  {
    id: "ms-chicken-parm-meatloaf",
    name: "Chicken Parmesan Meatloaf",
    category: "Poultry",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/healthy-high-protein-chicken-parm-meatloaf",
    image: "/images/recipes/ms-chicken-parm-meatloaf.png",
    calories: 350, protein: 40, carbs: 15, fat: 14, servings: 6,
    prepTime: 15, cookTime: 40,
    ingredients: [
      { item: "Ground chicken", amount: "700g" },
      { item: "Marinara sauce", amount: "200g" },
      { item: "Mozzarella cheese", amount: "80g" },
      { item: "Breadcrumbs", amount: "60g" },
      { item: "Egg", amount: "1" },
      { item: "Parmesan cheese", amount: "30g" },
      { item: "Italian seasoning", amount: "1 tbsp" },
    ],
    instructions: [
      "Mix ground chicken with breadcrumbs, egg, parmesan, and seasoning.",
      "Form into a loaf in a baking dish.",
      "Top with marinara and mozzarella.",
      "Bake at 190°C for 35-40 minutes until cooked through.",
    ],
    tags: ["high-protein", "meal-prep", "batch-cook"],
  },

  // ── Vegetarian ─────────────────────────────────────────────────────────────
  {
    id: "roasted-veg-feta-tart",
    name: "Roasted Veg & Feta Tart",
    category: "Vegetarian",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/roast-veg-feta-pastry-tart/",
    image: "/images/recipes/roasted-veg-feta-tart.png",
    calories: 282, protein: 9, carbs: 23, fat: 16, servings: 4,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Puff pastry sheet", amount: "1" },
      { item: "Mixed roast vegetables", amount: "300g" },
      { item: "Feta cheese (crumbled)", amount: "100g" },
      { item: "Pesto", amount: "2 tbsp" },
      { item: "Egg (beaten, for glaze)", amount: "1" },
    ],
    instructions: [
      "Roll out pastry on a baking sheet. Score a 2cm border.",
      "Spread pesto inside the border. Top with roasted veg and feta.",
      "Brush border with beaten egg. Bake at 200°C for 18-20 minutes.",
    ],
    tags: ["quick", "vegetarian"],
  },
  {
    id: "one-tray-halloumi-wraps",
    name: "One-Tray Halloumi Wraps",
    category: "Vegetarian",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/one-tray-halloumi-wraps-protein-plates-recipe-book/",
    image: "/images/recipes/one-tray-halloumi-wraps.png",
    calories: 467, protein: 21, carbs: 35, fat: 25, servings: 2,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Halloumi (sliced)", amount: "200g" },
      { item: "Tortilla wraps", amount: "2" },
      { item: "Bell pepper (sliced)", amount: "1" },
      { item: "Courgette (sliced)", amount: "1" },
      { item: "Olive oil", amount: "1 tbsp" },
      { item: "Hummus", amount: "4 tbsp" },
    ],
    instructions: [
      "Arrange halloumi, peppers, and courgette on a baking tray. Drizzle with oil.",
      "Bake at 200°C for 18-20 minutes until halloumi is golden.",
      "Spread hummus on tortillas. Fill with baked halloumi and veg.",
    ],
    tags: ["vegetarian", "meal-prep", "one-tray"],
  },
  {
    id: "halloumi-harissa-bake",
    name: "One-Pan Halloumi & Harissa Bake",
    category: "Vegetarian",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/one-pan-halloumi-harissa-bake/",
    image: "/images/recipes/halloumi-harissa-bake.png",
    calories: 409, protein: 16, carbs: 22, fat: 25, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "Halloumi (sliced)", amount: "250g" },
      { item: "Harissa paste", amount: "2 tbsp" },
      { item: "Aubergine (cubed)", amount: "1" },
      { item: "Cherry tomatoes", amount: "200g" },
      { item: "Chickpeas (drained)", amount: "200g" },
      { item: "Olive oil", amount: "1 tbsp" },
    ],
    instructions: [
      "Toss aubergine, tomatoes, and chickpeas with harissa and olive oil.",
      "Spread in a baking dish. Top with halloumi slices.",
      "Bake at 200°C for 20-25 minutes until halloumi is golden.",
    ],
    tags: ["vegetarian", "one-pan", "meal-prep"],
  },
  {
    id: "ms-veggie-quesadilla",
    name: "Chipotle Cheddar Vegetarian Quesadilla",
    category: "Vegetarian",
    source: "Muscle & Strength",
    sourceUrl: "https://www.muscleandstrength.com/recipes/high-protein-vegetarian-quesadilla",
    calories: 380, protein: 22, carbs: 32, fat: 18, servings: 2,
    prepTime: 10, cookTime: 10,
    ingredients: [
      { item: "Flour tortillas", amount: "2" },
      { item: "Black beans (mashed)", amount: "100g" },
      { item: "Cheddar cheese", amount: "80g" },
      { item: "Bell pepper (diced)", amount: "1" },
      { item: "Chipotle in adobo", amount: "1 tsp" },
      { item: "Greek yogurt (for dipping)", amount: "60g" },
    ],
    instructions: [
      "Mash black beans with chipotle.",
      "Spread on tortillas. Top with cheese and peppers.",
      "Fold and grill on a pan until crispy and cheese melts.",
      "Serve with Greek yogurt for dipping.",
    ],
    tags: ["vegetarian", "quick"],
  },

  // ── Plant-based ────────────────────────────────────────────────────────────
  {
    id: "one-pot-lentil-dahl",
    name: "One-Pot Lentil Dahl",
    category: "Plant-based",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/one-pot-lentil-dahl-easy-vegan-meal-prep/",
    image: "/images/recipes/one-pot-lentil-dahl.png",
    calories: 191, protein: 9, carbs: 14, fat: 9, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "Red lentils", amount: "200g" },
      { item: "Coconut milk", amount: "200ml" },
      { item: "Vegetable stock", amount: "400ml" },
      { item: "Onion (diced)", amount: "1" },
      { item: "Garlic (minced)", amount: "3 cloves" },
      { item: "Garam masala", amount: "2 tsp" },
      { item: "Turmeric", amount: "1 tsp" },
    ],
    instructions: [
      "Sauté onion and garlic. Add spices and cook 1 minute.",
      "Add lentils, stock, and coconut milk. Bring to a boil.",
      "Simmer 20-25 minutes until lentils are soft and creamy.",
      "Serve with naan bread or rice.",
    ],
    tags: ["plant-based", "meal-prep", "one-pot"],
  },
  {
    id: "vegan-meatball-sub",
    name: "Vegan \"Meatball\" Sub",
    category: "Plant-based",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/vegan-meatball-sub/",
    image: "/images/recipes/vegan-meatball-sub.png",
    calories: 498, protein: 29, carbs: 65, fat: 11, servings: 2,
    prepTime: 15, cookTime: 20,
    ingredients: [
      { item: "Kidney beans (drained)", amount: "200g" },
      { item: "Breadcrumbs", amount: "60g" },
      { item: "Sub rolls", amount: "2" },
      { item: "Marinara sauce", amount: "200g" },
      { item: "Nutritional yeast", amount: "2 tbsp" },
      { item: "Smoked paprika", amount: "1 tsp" },
    ],
    instructions: [
      "Mash kidney beans. Mix with breadcrumbs, nutritional yeast, and paprika.",
      "Form into meatball shapes. Bake at 200°C for 15 minutes.",
      "Warm marinara sauce. Add meatballs and simmer 5 minutes.",
      "Fill sub rolls with meatballs and sauce.",
    ],
    tags: ["plant-based", "meal-prep", "high-protein"],
  },
  {
    id: "vegan-fajitas",
    name: "15-Minute Vegan Portobello Fajitas",
    category: "Plant-based",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/15-minute-vegan-meal-ultimate-fajitas/",
    image: "/images/recipes/vegan-fajitas.png",
    calories: 439, protein: 12, carbs: 35, fat: 15, servings: 2,
    prepTime: 5, cookTime: 10,
    ingredients: [
      { item: "Portobello mushrooms (sliced)", amount: "300g" },
      { item: "Tortilla wraps", amount: "2" },
      { item: "Bell peppers (sliced)", amount: "2" },
      { item: "Onion (sliced)", amount: "1" },
      { item: "Fajita seasoning", amount: "2 tbsp" },
      { item: "Guacamole", amount: "60g" },
    ],
    instructions: [
      "Stir-fry mushrooms, peppers, and onion with fajita seasoning.",
      "Warm tortillas. Fill with fajita mix and guacamole.",
    ],
    tags: ["plant-based", "quick"],
  },
  {
    id: "crispy-tofu-teriyaki-noodles",
    name: "Crispy Tofu & Teriyaki Noodles",
    category: "Plant-based",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/crispy-tofu-teriyaki-noodle-meal-prep/",
    image: "/images/recipes/crispy-tofu-teriyaki-noodles.png",
    calories: 462, protein: 17, carbs: 67, fat: 14, servings: 2,
    prepTime: 10, cookTime: 15,
    ingredients: [
      { item: "Firm tofu (cubed)", amount: "200g" },
      { item: "Udon noodles", amount: "200g" },
      { item: "Teriyaki sauce", amount: "4 tbsp" },
      { item: "Broccoli (florets)", amount: "150g" },
      { item: "Cornflour", amount: "2 tbsp" },
      { item: "Sesame oil", amount: "1 tbsp" },
    ],
    instructions: [
      "Press tofu dry. Coat in cornflour. Fry in sesame oil until crispy.",
      "Cook noodles according to package directions.",
      "Steam broccoli. Toss noodles and broccoli with teriyaki sauce.",
      "Top with crispy tofu.",
    ],
    tags: ["plant-based", "meal-prep"],
  },
  {
    id: "vegan-lentil-bolognese",
    name: "Vegan Lentil Bolognese",
    category: "Plant-based",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/vegan-lentil-bolognese-meal-prep-recipe/",
    image: "/images/recipes/vegan-lentil-bolognese.png",
    calories: 486, protein: 21, carbs: 86, fat: 6, servings: 4,
    prepTime: 10, cookTime: 25,
    ingredients: [
      { item: "Green lentils", amount: "200g" },
      { item: "Spaghetti", amount: "350g" },
      { item: "Chopped tomatoes (canned)", amount: "400g" },
      { item: "Onion (diced)", amount: "1" },
      { item: "Carrot (grated)", amount: "1" },
      { item: "Garlic (minced)", amount: "3 cloves" },
      { item: "Italian seasoning", amount: "1 tbsp" },
    ],
    instructions: [
      "Sauté onion, carrot, and garlic until softened.",
      "Add lentils, tomatoes, and 400ml water. Simmer 25 minutes.",
      "Cook spaghetti. Serve bolognese over pasta.",
    ],
    tags: ["plant-based", "meal-prep", "batch-cook"],
  },
  {
    id: "buffalo-cauliflower-tacos",
    name: "Vegan Buffalo Cauliflower Tacos",
    category: "Plant-based",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/vegan-buffalo-cauliflower-tacos/",
    image: "/images/recipes/buffalo-cauliflower-tacos.png",
    calories: 278, protein: 11, carbs: 23, fat: 15, servings: 2,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Cauliflower (florets)", amount: "1 head" },
      { item: "Buffalo sauce", amount: "60ml" },
      { item: "Corn tortillas", amount: "4" },
      { item: "Avocado (sliced)", amount: "1" },
      { item: "Red cabbage (shredded)", amount: "100g" },
      { item: "Lime juice", amount: "1 tbsp" },
    ],
    instructions: [
      "Toss cauliflower in buffalo sauce. Bake at 220°C for 18-20 minutes.",
      "Warm tortillas. Fill with cauliflower, avocado, and cabbage.",
      "Squeeze lime juice over and serve.",
    ],
    tags: ["plant-based", "quick"],
  },
  {
    id: "vegan-mac-n-cheese",
    name: "Vegan Mac 'N' Cheese",
    category: "Plant-based",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/vegan-mac-n-cheese/",
    image: "/images/recipes/vegan-mac-n-cheese.png",
    calories: 452, protein: 16, carbs: 63, fat: 13, servings: 4,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Macaroni pasta", amount: "350g" },
      { item: "Butternut squash (cubed)", amount: "300g" },
      { item: "Nutritional yeast", amount: "4 tbsp" },
      { item: "Oat milk", amount: "200ml" },
      { item: "Garlic (minced)", amount: "2 cloves" },
      { item: "Mustard powder", amount: "1 tsp" },
    ],
    instructions: [
      "Boil butternut squash until soft, about 15 minutes.",
      "Blend squash with nutritional yeast, oat milk, garlic, and mustard.",
      "Cook pasta. Toss with cheese sauce. Season to taste.",
    ],
    tags: ["plant-based", "comfort-food", "meal-prep"],
  },

  // ── Sweet ──────────────────────────────────────────────────────────────────
  {
    id: "protein-cheesecake",
    name: "Protein Cheesecake",
    category: "Sweet",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/protein-cheesecake-recipe/",
    image: "/images/recipes/protein-cheesecake.png",
    calories: 180, protein: 25, carbs: 10, fat: 4, servings: 8,
    prepTime: 15, cookTime: 0,
    ingredients: [
      { item: "Greek yogurt (nonfat)", amount: "500g" },
      { item: "Whey protein (vanilla)", amount: "60g" },
      { item: "Oat biscuit base", amount: "8 biscuits" },
      { item: "Gelatin sheets", amount: "3" },
      { item: "Sweetener", amount: "2 tbsp" },
    ],
    instructions: [
      "Crush biscuits and press into base of a springform tin.",
      "Mix yogurt, protein powder, and sweetener until smooth.",
      "Dissolve gelatin and fold into yogurt mix. Pour over base.",
      "Refrigerate at least 4 hours until set.",
    ],
    tags: ["high-protein", "low-calorie", "no-bake"],
  },
  {
    id: "hp-protein-cookie",
    name: "Ultimate High-Protein Cookie",
    category: "Sweet",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/the-ultimate-high-protein-cookie/",
    image: "/images/recipes/hp-protein-cookie.png",
    calories: 425, protein: 65, carbs: 24, fat: 22, servings: 1,
    prepTime: 5, cookTime: 12,
    ingredients: [
      { item: "Whey protein powder", amount: "30g" },
      { item: "Peanut butter", amount: "2 tbsp" },
      { item: "Oats", amount: "30g" },
      { item: "Egg white", amount: "1" },
      { item: "Dark chocolate chips", amount: "15g" },
    ],
    instructions: [
      "Mix protein powder, oats, peanut butter, and egg white into a dough.",
      "Fold in chocolate chips. Form into a large cookie.",
      "Bake at 180°C for 10-12 minutes until golden.",
    ],
    tags: ["high-protein", "quick"],
  },
  {
    id: "fudgey-protein-brownies",
    name: "Fudgey Chocolate Protein Brownies",
    category: "Sweet",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/fudgey-chocolate-protein-brownies/",
    image: "/images/recipes/fudgey-protein-brownies.png",
    calories: 99, protein: 10, carbs: 10, fat: 2, servings: 9,
    prepTime: 10, cookTime: 20,
    ingredients: [
      { item: "Chocolate whey protein", amount: "60g" },
      { item: "Cocoa powder", amount: "30g" },
      { item: "Greek yogurt (nonfat)", amount: "200g" },
      { item: "Egg", amount: "1" },
      { item: "Sweetener", amount: "3 tbsp" },
      { item: "Baking powder", amount: "1 tsp" },
    ],
    instructions: [
      "Mix all dry ingredients. Add yogurt and egg until smooth.",
      "Pour into a greased 8x8 tin. Bake at 180°C for 18-20 minutes.",
      "Cool before cutting into 9 pieces.",
    ],
    tags: ["high-protein", "low-calorie"],
  },
  {
    id: "protein-balls",
    name: "Protein Balls",
    category: "Sweet",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/only-protein-balls-recipe-you-need/",
    image: "/images/recipes/protein-balls.png",
    calories: 84, protein: 5, carbs: 8, fat: 4, servings: 12,
    prepTime: 10, cookTime: 0,
    ingredients: [
      { item: "Rolled oats", amount: "100g" },
      { item: "Peanut butter", amount: "60g" },
      { item: "Honey", amount: "2 tbsp" },
      { item: "Whey protein", amount: "30g" },
      { item: "Dark chocolate chips", amount: "30g" },
    ],
    instructions: [
      "Combine all ingredients in a bowl and mix well.",
      "Roll into 12 balls. Refrigerate at least 1 hour.",
      "Store in the fridge for up to 5 days.",
    ],
    tags: ["high-protein", "no-bake", "snack"],
  },

  // ── Air Fryer ──────────────────────────────────────────────────────────────
  {
    id: "air-fryer-pizza",
    name: "Air Fryer Pizza (3 Ways)",
    category: "Air Fryer",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/air-fryer-pizza-recipe/",
    image: "/images/recipes/air-fryer-pizza.png",
    calories: 404, protein: 24, carbs: 70, fat: 2, servings: 1,
    prepTime: 5, cookTime: 10,
    ingredients: [
      { item: "Tortilla wrap", amount: "1" },
      { item: "Passata", amount: "2 tbsp" },
      { item: "Mozzarella (grated)", amount: "40g" },
      { item: "Toppings of choice", amount: "as needed" },
    ],
    instructions: [
      "Spread passata on tortilla. Add mozzarella and chosen toppings.",
      "Air fry at 180°C for 8-10 minutes until crispy and cheese is melted.",
    ],
    tags: ["quick", "low-fat"],
  },
  {
    id: "air-fryer-buffalo-wings",
    name: "Air Fryer Buffalo Chicken Wings",
    category: "Air Fryer",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/air-fryer-buffalo-chicken-wings/",
    image: "/images/recipes/air-fryer-buffalo-wings.png",
    calories: 243, protein: 20, carbs: 7, fat: 16, servings: 4,
    prepTime: 5, cookTime: 20,
    ingredients: [
      { item: "Chicken wings", amount: "600g" },
      { item: "Buffalo sauce", amount: "60ml" },
      { item: "Baking powder", amount: "1 tbsp" },
      { item: "Salt", amount: "1 tsp" },
    ],
    instructions: [
      "Pat wings dry. Toss with baking powder and salt.",
      "Air fry at 200°C for 20 minutes, shaking halfway.",
      "Toss cooked wings in buffalo sauce and serve.",
    ],
    tags: ["high-protein", "low-carb"],
  },
  {
    id: "air-fryer-teriyaki-salmon",
    name: "Air Fryer Teriyaki Salmon Bowl",
    category: "Air Fryer",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/easy-air-fryer-teriyaki-salmon/",
    image: "/images/recipes/air-fryer-teriyaki-salmon.png",
    calories: 600, protein: 40, carbs: 75, fat: 35, servings: 2,
    prepTime: 10, cookTime: 12,
    ingredients: [
      { item: "Salmon fillets", amount: "2" },
      { item: "Teriyaki sauce", amount: "3 tbsp" },
      { item: "Sushi rice (cooked)", amount: "250g" },
      { item: "Edamame", amount: "80g" },
      { item: "Cucumber (sliced)", amount: "1/2" },
      { item: "Avocado (sliced)", amount: "1" },
    ],
    instructions: [
      "Brush salmon with teriyaki sauce.",
      "Air fry at 190°C for 10-12 minutes.",
      "Serve over sushi rice with edamame, cucumber, and avocado.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "air-fryer-chicken-skewers",
    name: "Air Fryer Chicken Skewers",
    category: "Air Fryer",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/air-fryer-chicken-skewers/",
    image: "/images/recipes/air-fryer-chicken-skewers.png",
    calories: 356, protein: 35, carbs: 47, fat: 4, servings: 4,
    prepTime: 15, cookTime: 12,
    ingredients: [
      { item: "Chicken breast (cubed)", amount: "500g" },
      { item: "Greek yogurt", amount: "100g" },
      { item: "Lemon juice", amount: "2 tbsp" },
      { item: "Garlic powder", amount: "1 tsp" },
      { item: "Paprika", amount: "1 tsp" },
      { item: "Couscous", amount: "200g" },
    ],
    instructions: [
      "Marinate chicken in yogurt, lemon, garlic, and paprika for 30 minutes.",
      "Thread onto skewers. Air fry at 200°C for 10-12 minutes.",
      "Cook couscous. Serve skewers over couscous with salad.",
    ],
    tags: ["high-protein", "low-fat", "meal-prep"],
  },
  {
    id: "air-fryer-popcorn-chicken",
    name: "Air Fryer Popcorn Chicken",
    category: "Air Fryer",
    source: "MyProtein",
    sourceUrl: "https://www.myprotein.com/thezone/recipe/air-fryer-popcorn-chicken-fakeaway/",
    image: "/images/recipes/air-fryer-popcorn-chicken.png",
    calories: 347, protein: 43, carbs: 21, fat: 9, servings: 2,
    prepTime: 10, cookTime: 12,
    ingredients: [
      { item: "Chicken breast (bite-sized)", amount: "400g" },
      { item: "Egg white", amount: "1" },
      { item: "Panko breadcrumbs", amount: "60g" },
      { item: "Paprika", amount: "1 tsp" },
      { item: "Garlic powder", amount: "1 tsp" },
    ],
    instructions: [
      "Dip chicken pieces in egg white. Coat in panko mixed with spices.",
      "Air fry at 200°C for 10-12 minutes, shaking halfway.",
      "Serve with dipping sauce of choice.",
    ],
    tags: ["high-protein", "low-fat", "quick"],
  },
];

// ── Search helpers ───────────────────────────────────────────────────────────

export function searchRecipeDatabase(query: string, limit = 20): RecipePreset[] {
  if (!query || query.trim().length < 1) return [];
  const q = query.toLowerCase().trim();
  return recipeDatabase
    .filter(
      (r) =>
        r.name.toLowerCase().includes(q) ||
        r.category.toLowerCase().includes(q) ||
        r.source.toLowerCase().includes(q) ||
        r.tags?.some((t) => t.toLowerCase().includes(q))
    )
    .slice(0, limit);
}

export function getRecipesByCategory(category: RecipeCategory): RecipePreset[] {
  return recipeDatabase.filter((r) => r.category === category);
}

export function getRecipeById(id: string): RecipePreset | undefined {
  return recipeDatabase.find((r) => r.id === id);
}
